site_name: "PayCaddy API"
nav:
  - Introduction: index.md

  - Flows:
      - Flow Overview: overviewFlow.md #done
      - User Creation: userFlow.md #done
      - Card Creation: cardFlow.md #done
      - Funding Flow:
          - Prefunded: prefundedFlow.md #done
          - Just-In-Time: JITflow.md #done

  - Card Issuing API:
      - Users:
          - User Creation & Retrieval: user.md #done
          - User Creation & Retrieval V2: userv2.md #done
          - Edit or Update User Information: editUser.md
          - KYC Verification: kyc.md #done
      - Wallets:
          - Wallet Creation & Retrieval: wallet.md #done
          - Wallet Operations: wallet_ops.md #done
      - Cards:
          - Card Creation & Retrieval: card.md #done
          - Card Operations: card_ops.md #done
      - Transactions:
          - Prefunded Transactions: prefundedTRX.md #done
          - Just-In-Time Funding: JITtrx.md #done
          - Settlement: settlement.md #done
          - Other Transactions: otherTransactions.md #done
          - Transaction Data Retrieval: transactionLists.md #done
      - Webhooks: notificationsEnlist.md
  - Credit Core (beta):
      - Credit Flows: creditFlow.md
      - Credit Core API: creditCore.md
  - Interfaces:
      - WhatsApp Chatbot: chatbot.md
      - CPM Backoffice: backoffice.md
  - Changelog: changelog.md

theme:
  name: material
  logo: assets/imgs/logo.svg
  favicon: assets/imgs/logo.svg
  icon:
    admonition:
      info: octicons/info-16
      tip: octicons/squirrel-16
      warning: octicons/alert-16
      danger: octicons/zap-16

  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: white
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

  features:
    - navigation.footer
    - content.code.copy
    - content.tabs.link
    - navigation.sections
  collapse: false
  font:
    text: Montserrat

plugins:
  - search:
      enabled: true
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: English
          build: true

        - locale: es
          name: Espa√±ol
          build: true

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
extra_css:
  - stylesheets/extra.css

# Footer config
extra:
  generator: false
