site_name: "NeoBank API"
nav:
  - Introduction: index.md

  - Flows:
      - User Creation Flow: userFlow.md
      - Card Creation Flow: flow.md
      - Prefunded Flow: prefundedFlow.md
      - Just-In-Time Funding Flow: JITflow.md

  - Card Issuing API:
      - Users:
          - Creation & Retrieval: user.md
          - KYC Verification: kyc.md
      - Wallets:
          - Create & Retrieve: wallet.md
          - Wallet Operations: wallet_op.md
      - Cards:
          - Create & Retrieve: card.md
          - Card Operations: card_operations.md
      - Card Transactions:
          - Prefunded: trxNotification.md
          - Just-In-Time Funding: JITtrxs.md
          - Settlement: settlement.md
          - Retrieval: transactionLists.md
      - Webhooks: notificationsEnlist.md
  - Credit Core: creditCore.md
  - WhatsApp Chatbot: chatbot.md
  - CPM Backoffice: backoffice.md
  - Changelog: changelog.md

theme:
  name: material
  logo: assets/imgs/logo.svg
  favicon: assets/imgs/logo.svg
  icon:
    admonition:
      info: octicons/info-16
      tip: octicons/squirrel-16
      warning: octicons/alert-16
      danger: octicons/zap-16

  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: white
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue grey
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

  features:
    - navigation.footer
    - content.code.copy
    - content.tabs.link
    - navigation.sections
  collapse: false
  font:
    text: Montserrat
  language: en

plugins:
  - search:
      enabled: true
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: English
          build: true

        - locale: es
          name: Espa√±ol
          build: true
  - mermaid2:
    enabled: true

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
extra_css:
  - stylesheets/extra.css

# Footer config
extra:
  generator: false
