site_name: "NeoBank API Documentation"
nav:
  - Home: index.md
  - Flows:
      - Prefunded Flow: prefunded.md
      - Just In Time Funding Flow: JIT.md
      - Integrated KYC: integratedKYC.md
      - Delegated KYC: delegatedKYC.md
  - Card Issuing API:
      - Users: user.md
      - Wallets:
          - Intro: introwallet.md
          - Creation and Retrieval: createwallet.md
          - Wallet Operations: wallet_op.md
      - Cards:
          - Creation and Retrieval: card.md
          - Card Operations: card_operations.md
      - Transactions:
          - Prefunded Transaction Types: prefundedTrx.md
          - Just In Time Funding: JITtrx.md
          - Retrieval: TransactionsRetrieval.md
      - Webhook Notifications:
          - Transaction Notifications: trxWebhooks.md
          - Integrated KYC Notifications: kycWebhooks.md
  - Credit Core: creditCore.md
  - WhatsApp Chatbot: chatbot.md
  - CPM Backoffice: backoffice.md

theme:
  name: material
  logo: assets/imgs/logo.svg
  favicon: assets/imgs/logo.svg
  icon:
    admonition:
      info: octicons/info-16
      tip: octicons/squirrel-16
      warning: octicons/alert-16
      danger: octicons/zap-16

  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: white
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue grey
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

  features:
    - navigation.footer
    - content.code.copy
    - content.tabs.link
    - navigation.sections
  collapse: false
  font:
    text: Montserrat
  language: en

plugins:
  - search:
      enabled: true
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: English
          build: true

        - locale: es
          name: Espa√±ol
          build: true

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.mermaid
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
extra_css:
  - stylesheets/extra.css

# Footer config
extra:
  generator: false
