name: Generate Changelog

on:
  release:
    types: [published]
permissions:
  contents: write

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    steps:
      # Checkout do código
      - name: Check out code
        uses: actions/checkout@v3

      # Buscar todas as branches
      - name: Fetch all branches
        run: git fetch --all

      # Garantir que estamos na branch principal
      - name: Checkout main branch
        run: git checkout main

      # Gerar o arquivo de changelog
      - name: Generate Changelog File
        run: |
          echo "## Changelog da Versão ${GITHUB_REF##*/}" > ./chatbot-doc/docs/changelog.md
          echo "" >> changelog.md
          echo "$(gh release view ${GITHUB_REF##*/} --json body --jq '.body')" >> ./chatbot-doc/docs/changelog.md

      # Configurar o Git e realizar o commit
      - name: Commit and Push Changelog
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ./chatbot-doc/docs/changelog.md
          git commit -m "Update changelog for ${GITHUB_REF##*/}"
          git push origin main
