name: Release Drafter

on:
  workflow_dispatch:

  # pull_request event is required only for autolabeler
  pull_request:
    # Only following types are handled by the action, but one can default to all as well
    types: opened

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update ./chatbot-doc/docs/CHANGELOG.md
        run: |
          CHANGELOG_PATH="./chatbot-doc/docs/changelog.md"
          
          # Garante que o arquivo existe
          mkdir -p "$(dirname "$CHANGELOG_PATH")"
          touch "$CHANGELOG_PATH"

          # Cria o novo conteúdo do changelog
          echo "## Release Notes (Generated on $(date +'%Y-%m-%d'))" > changelog-new.md
          echo "" >> changelog-new.md
          echo "${{ steps.release.outputs.body }}" >> changelog-new.md
          echo "" >> changelog-new.md
          cat "$CHANGELOG_PATH" >> changelog-new.md
          mv changelog-new.md "$CHANGELOG_PATH"

      # Faz commit das alterações
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ./chatbot-doc/docs/CHANGELOG.md
          git commit -m "chore: update CHANGELOG.md with latest release notes"
          git push