name: 'Release new version'

on:
  ##Runs manually
  workflow_dispatch:


jobs:
  update_changelog:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Generate release notes with Release Drafter
        id: release
        uses: release-drafter/release-drafter@v5
        with:
          config-name: .github/release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Update ./chatbot-doc/docs/CHANGELOG.md
        run: |
          CHANGELOG_PATH="./chatbot-doc/docs/changelog.md"
          
          # Garante que o arquivo existe
          mkdir -p "$(dirname "$CHANGELOG_PATH")"
          touch "$CHANGELOG_PATH"

          # Cria o novo conteúdo do changelog
          echo "## Release Notes (Generated on $(date +'%Y-%m-%d'))" > changelog-new.md
          echo "" >> changelog-new.md
          echo "${{ steps.release.outputs.body }}" >> changelog-new.md
          echo "" >> changelog-new.md
          cat "$CHANGELOG_PATH" >> changelog-new.md
          mv changelog-new.md "$CHANGELOG_PATH"

      # Faz commit das alterações
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ./chatbot-doc/docs/CHANGELOG.md
          git commit -m "chore: update CHANGELOG.md with latest release notes"
          git push